PROJECT_STATUS_IN_PROGRESS = "P"
PROJECT_STATUS_ARCHIVED = "A"
PROJECT_STATUS_COMPLETE = "C"
PROJECT_STATUS_HOLD = "H"

TICKET_STATUS_NOT_STARTED = "N"
TICKET_STATUS_PROGRESS = "P"
TICKET_STATUS_FINISHED = "F"